# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0002_canvasnode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasNode',
        ),
    ]
