# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0006_auto_20180822_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('P', 'Poster'), ('W', 'Watcher')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_notifications', to='doops.CanvasNode')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='doops.User')),
            ],
        ),
    ]
