# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0008_auto_20180826_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doops.CanvasNode')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_canvases', to='doops.User')),
                ('watched_users', models.ManyToManyField(related_name='watched_canvases', to='doops.User')),
            ],
        ),
    ]
