# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0009_canvasnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('P', 'Poster'), ('W', 'Watcher')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_notifications', to='doops.CanvasNode'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='doops.User'),
        ),
    ]
