# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0011_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasnode',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_canvases', to='doops.User'),
        ),
    ]
