# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doops', '0014_auto_20180830_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_canvas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doops.CanvasNode')),
                ('reporter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doops.User')),
            ],
        ),
    ]
